repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    exclude: ^README.md$
  - id: no-commit-to-branch
  - id: end-of-file-fixer

- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.2
  hooks:
  - id: parsable-R
  - id: use-tidy-description
  - id: roxygenize
  - id: no-print-statement
