#!/usr/bin/env Rscript 

# This script generates the RDA datasets and their
# accompanying documentation for {lovecraftr} using
# the raw txt files in data-raw/corpus


raw_txt_path <- file.path("data-raw", "corpus")
data_docs_file <- file.path("R", "data.R")

header <- "# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################
"

generate_data <- function() {
  corpus <- list.files(
    path = raw_txt_path,
    full.names = FALSE,
    recursive = FALSE
  )

  file.remove(data_docs_file)

  docs_template <- "{header}
#' @title \"{title}\"
#'
#' @description A dataset containing UTF-8 plain text of
#'   H. P. Lovecraft's \"{title}\"
#'
#' @examples
#' data(\"{dataset_name}\")
#' lovecraftr::{txt}
#'
#' @format A character vector with {scales::number(length(text), big.mark = \",\")} elements,
#'   with roughly 80 characters per line
#'
#' @source Public domain
\"{dataset_name}\"

##################################################################################
"
  docs <- c()
  dataframes_list <- list()
  for (txt in corpus) {
    txt_path <- file.path(raw_txt_path, txt)
    text <- readr::read_lines(txt_path)
    dataset_name <- as.name(txt)
    assign(txt, text)
    do.call(usethis::use_data, list(dataset_name, overwrite = TRUE))

    title <- text |>
      head(1) |>
      stringr::str_to_title()

    dataset_docs <- glue::glue(docs_template)
    docs <- c(docs, dataset_docs)

    dataframes_list[[dataset_name]] <- tibble::tibble(
      title = title,
      text = text
    )
  }

  lovecraft <- dplyr::bind_rows(dataframes_list)
  corpus_docs <- glue::glue("{header}
#' @title Lovecraft
#'
#' @description A dataset containing UTF-8 plain text of
#'   all the H. P. Lovecraft works available in {{lovecraftr}}
#'
#' @examples
#' data(\"lovecraft\")
#' lovecraftr::lovecraft
#'
#' @format A tibble with {scales::number(nrow(lovecraft), big.mark = \",\")} rows and {ncol(lovecraft)} columns:
#' \\describe{{
#'   \\item{{title}}{{Title of the work}}
#'   \\item{{text}}{{~80 characters of text from the title}}
#' }}
#'
#' @source Public domain
\"lovecraft\"
")

  docs <- c(docs, corpus_docs)
  usethis::use_data(lovecraft, overwrite = TRUE)

  doc_file <- file(data_docs_file, "a")
  write(docs, file = doc_file)
  close(doc_file)
}

generate_data()
