#!/usr/bin/env Rscript 

# This script generates the RDA datasets and their
# accompanying documentation for {lovecraftr} using
# the raw txt files in data-raw/corpus


raw_txt_path <- file.path("data-raw", "corpus")
data_docs_file <- file.path("R", "data.R")

generate_data <- function() {
  corpus <- list.files(
    path = raw_txt_path,
    full.names = FALSE,
    recursive = FALSE
  )

  file.remove(data_docs_file)

  docs <- readr::read_lines("# This file is generated by a script, do not edit by hand
# If changes are made to the raw txt files or the docs
# template in data-raw/generate_docs(), rerun generate_docs()
# to regenerate new dataset documentation


")

  docs_template <- "#' @title \"{name}\"
#'
#' @description A dataset containing UTF-8 plain text of
#'   H. P. Lovecraft's \"{name}\"
#'
#' @examples
#' data(\"{as.name(txt)}\")
#' lovecraftr::{txt}
#'
#' @format A character vector with {scales::number(length(text), big.mark = \",\")} elements,
#'   with roughly 80 characters per line
#'
#' @source Public domain
\"{as.name(txt)}\"


"

  dataframes_list <- list()
  for (txt in corpus) {
    txt_path <- file.path(raw_txt_path, txt)
    text <- readr::read_lines(txt_path)
    assign(txt, text)
    do.call(usethis::use_data, list(as.name(txt), overwrite = TRUE))

    name <- txt |>
      stringr::str_replace_all("_", " ") |>
      stringr::str_to_title()

    dataset_docs <- glue::glue(docs_template)
    docs <- c(docs, dataset_docs)

    dataframes_list[[name]] <- tibble::tibble(
      title = name,
      text = text
    )
  }

  lovecraft <- dplyr::bind_rows(dataframes_list)
  corpus_docs <- glue::glue("#' @title Lovecraft
#'
#' @description A dataset containing UTF-8 plain text of
#'   all the H. P. Lovecraft works available in {{lovecraftr}}
#'
#' @examples
#' data(\"lovecraft\")
#' lovecraftr::lovecraft
#'
#' @format A tibble with {scales::number(nrow(lovecraft), big.mark = \",\")} rows and {ncol(lovecraft)} columns:
#' \\describe{{
#'   \\item{{title}}{{Title of the work}}
#'   \\item{{text}}{{~80 characters of text from the title}}
#' }}
#'
#' @source Public domain
\"lovecraft\"


")

  docs <- c(docs, corpus_docs)
  usethis::use_data(lovecraft, overwrite = TRUE)

  doc_file <- file(data_docs_file, "a")
  write(docs, file = doc_file)
  close(doc_file)
}

generate_data()
