#!/usr/bin/env Rscript

# This script generates the RDA datasets and their
# accompanying documentation for {lovecraftr} using
# the raw txt files in data-raw/corpus

devtools::load_all()

title_case <- function(x) {
  stopwords <- c("and", "of", "the", "on", "at", "in", "with", "to", "that", "a")
  words <- stringr::str_split(tolower(x), " ")[[1]]
  words <- ifelse(words %in% stopwords & seq_along(words) != 1, words, stringr::str_to_title(words))
  return(stringr::str_c(words, collapse = " "))
}

raw_txt_path <- file.path("data-raw", "corpus")
corpus <- list.files(raw_txt_path)
raw_txt_root <- "https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/"
rda_root <- "https://github.com/jrdnbradford/lovecraftr/raw/main/data/"
metadata <- lovecraftr:::metadata

data_docs_file <- file.path("R", "data.R")
file.remove(data_docs_file)

header <- "# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################
"

docs_template <- "{header}
#' @title {formatted_title}
#' @description A dataset containing text of H. P. Lovecraft's {formatted_title}.
#' @usage data({dataset_name})
#' @format A character vector with {num_vectors} elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets {type}
#' @source Public domain.
#'   For more details see the vignette:
#'   \\code{{vignette(\"copyright-status\", package = \"lovecraftr\")}}.
#'
#'   * {raw_txt_link}
#'   * {rda_link}
#' @md
\"{dataset_name}\"

##################################################################################
"
docs <- c()
dataset_list <- list()
for (txt in corpus) {
  txt_path <- file.path(raw_txt_path, txt)
  text <- readr::read_lines(txt_path)
  num_vectors <- scales::number(length(text), big.mark = ",")
  dataset_name <- as.name(txt)
  assign(txt, text)
  do.call(usethis::use_data, list(dataset_name, overwrite = TRUE, version = 3))

  type <- subset(metadata, title == dataset_name)$type
  title <- title_case(head(text, 1))
  formatted_title <-ifelse(type == "novella", paste0("_", title, "_"), paste0("\"", title, "\""))
  raw_txt_link <- paste0("[raw text file](", raw_txt_root, dataset_name, ")")
  rda_link <- paste0("[RDA file](", rda_root, dataset_name, ".rda)")
  dataset_docs <- glue::glue(docs_template)
  docs <- c(docs, dataset_docs)

  dataset_list[[dataset_name]] <- tibble::tibble(
    title = title,
    text = text
  )
}

lovecraft <- dplyr::bind_rows(dataset_list)
num_rows <- scales::number(nrow(lovecraft), big.mark = ",")
num_cols <- ncol(lovecraft)
corpus_docs <- glue::glue("{header}
#' @title Dataset of Lovecraft's Corpus
#' @description A dataset containing text of all the H. P. Lovecraft works available in this package.
#' @usage data(lovecraft)
#' @format A tibble with {num_rows} rows and {num_cols} columns:
#' \\describe{{
#'   \\item{{title}}{{Title of the work}}
#'   \\item{{text}}{{~80 characters of text from the title}}
#' }}
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   For more details see the vignette:
#'   \\code{{vignette(\"copyright-status\", package = \"lovecraftr\")}}.
#' @md
\"lovecraft\"
")

docs <- c(docs, corpus_docs)
usethis::use_data(lovecraft, overwrite = TRUE, version = 3)

doc_file <- file(data_docs_file, "a")
write(docs, file = doc_file)
close(doc_file)

roxygen2::roxygenize()
