# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "At The Mountains Of Madness"
#'
#' @description A dataset containing text of H. P. Lovecraft's "At The Mountains Of Madness"
#'
#' @examples
#' data("at_the_mountains_of_madness")
#' lovecraftr::at_the_mountains_of_madness
#'
#' @format A character vector with 3,579 elements, with roughly 80 characters per line
#'
#' @source Public domain
"at_the_mountains_of_madness"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Azathoth"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Azathoth"
#'
#' @examples
#' data("azathoth")
#' lovecraftr::azathoth
#'
#' @format A character vector with 37 elements, with roughly 80 characters per line
#'
#' @source Public domain
"azathoth"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Beyond The Wall Of Sleep"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Beyond The Wall Of Sleep"
#'
#' @examples
#' data("beyond_the_wall_of_sleep")
#' lovecraftr::beyond_the_wall_of_sleep
#'
#' @format A character vector with 361 elements, with roughly 80 characters per line
#'
#' @source Public domain
"beyond_the_wall_of_sleep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Celephais"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Celephais"
#'
#' @examples
#' data("celephais")
#' lovecraftr::celephais
#'
#' @format A character vector with 202 elements, with roughly 80 characters per line
#'
#' @source Public domain
"celephais"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Cool Air"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Cool Air"
#'
#' @examples
#' data("cool_air")
#' lovecraftr::cool_air
#'
#' @format A character vector with 292 elements, with roughly 80 characters per line
#'
#' @source Public domain
"cool_air"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Dagon"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Dagon"
#'
#' @examples
#' data("dagon")
#' lovecraftr::dagon
#'
#' @format A character vector with 187 elements, with roughly 80 characters per line
#'
#' @source Public domain
"dagon"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Dreams In The Witch-House"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Dreams In The Witch-House"
#'
#' @examples
#' data("dreams_in_the_witch_house")
#' lovecraftr::dreams_in_the_witch_house
#'
#' @format A character vector with 1,271 elements, with roughly 80 characters per line
#'
#' @source Public domain
"dreams_in_the_witch_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Ex Oblivione"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Ex Oblivione"
#'
#' @examples
#' data("ex_oblivione")
#' lovecraftr::ex_oblivione
#'
#' @format A character vector with 66 elements, with roughly 80 characters per line
#'
#' @source Public domain
"ex_oblivione"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Facts Concerning The Late Arthur Jermyn And His Family"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Facts Concerning The Late Arthur Jermyn And His Family"
#'
#' @examples
#' data("facts_concerning_the_late_arthur_jermyn_and_his_family")
#' lovecraftr::facts_concerning_the_late_arthur_jermyn_and_his_family
#'
#' @format A character vector with 303 elements, with roughly 80 characters per line
#'
#' @source Public domain
"facts_concerning_the_late_arthur_jermyn_and_his_family"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "From Beyond"
#'
#' @description A dataset containing text of H. P. Lovecraft's "From Beyond"
#'
#' @examples
#' data("from_beyond")
#' lovecraftr::from_beyond
#'
#' @format A character vector with 222 elements, with roughly 80 characters per line
#'
#' @source Public domain
"from_beyond"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "He"
#'
#' @description A dataset containing text of H. P. Lovecraft's "He"
#'
#' @examples
#' data("he")
#' lovecraftr::he
#'
#' @format A character vector with 360 elements, with roughly 80 characters per line
#'
#' @source Public domain
"he"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Herbert West: Reanimator"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Herbert West: Reanimator"
#'
#' @examples
#' data("herbert_west_reanimator")
#' lovecraftr::herbert_west_reanimator
#'
#' @format A character vector with 1,053 elements, with roughly 80 characters per line
#'
#' @source Public domain
"herbert_west_reanimator"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Hypnos"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Hypnos"
#'
#' @examples
#' data("hypnos")
#' lovecraftr::hypnos
#'
#' @format A character vector with 233 elements, with roughly 80 characters per line
#'
#' @source Public domain
"hypnos"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Imprisoned With The Pharaohs"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Imprisoned With The Pharaohs"
#'
#' @examples
#' data("imprisoned_with_the_pharoahs")
#' lovecraftr::imprisoned_with_the_pharoahs
#'
#' @format A character vector with 948 elements, with roughly 80 characters per line
#'
#' @source Public domain
"imprisoned_with_the_pharoahs"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "In The Vault"
#'
#' @description A dataset containing text of H. P. Lovecraft's "In The Vault"
#'
#' @examples
#' data("in_the_vault")
#' lovecraftr::in_the_vault
#'
#' @format A character vector with 272 elements, with roughly 80 characters per line
#'
#' @source Public domain
"in_the_vault"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Medusa's Coil"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Medusa's Coil"
#'
#' @examples
#' data("medusas_coil")
#' lovecraftr::medusas_coil
#'
#' @format A character vector with 1,443 elements, with roughly 80 characters per line
#'
#' @source Public domain
"medusas_coil"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Memory"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Memory"
#'
#' @examples
#' data("memory")
#' lovecraftr::memory
#'
#' @format A character vector with 31 elements, with roughly 80 characters per line
#'
#' @source Public domain
"memory"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Nyarlathotep"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Nyarlathotep"
#'
#' @examples
#' data("nyarlathotep")
#' lovecraftr::nyarlathotep
#'
#' @format A character vector with 97 elements, with roughly 80 characters per line
#'
#' @source Public domain
"nyarlathotep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Pickman's Model"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Pickman's Model"
#'
#' @examples
#' data("pickmans_model")
#' lovecraftr::pickmans_model
#'
#' @format A character vector with 455 elements, with roughly 80 characters per line
#'
#' @source Public domain
"pickmans_model"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Poetry Of The Gods"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Poetry Of The Gods"
#'
#' @examples
#' data("poetry_of_the_gods")
#' lovecraftr::poetry_of_the_gods
#'
#' @format A character vector with 157 elements, with roughly 80 characters per line
#'
#' @source Public domain
"poetry_of_the_gods"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Polaris"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Polaris"
#'
#' @examples
#' data("polaris")
#' lovecraftr::polaris
#'
#' @format A character vector with 129 elements, with roughly 80 characters per line
#'
#' @source Public domain
"polaris"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Alchemist"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Alchemist"
#'
#' @examples
#' data("the_alchemist")
#' lovecraftr::the_alchemist
#'
#' @format A character vector with 295 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_alchemist"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Beast In The Cave"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Beast In The Cave"
#'
#' @examples
#' data("the_beast_in_the_cave")
#' lovecraftr::the_beast_in_the_cave
#'
#' @format A character vector with 204 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_beast_in_the_cave"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Book"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Book"
#'
#' @examples
#' data("the_book")
#' lovecraftr::the_book
#'
#' @format A character vector with 95 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_book"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Call Of Cthulhu"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Call Of Cthulhu"
#'
#' @examples
#' data("the_call_of_cthulhu")
#' lovecraftr::the_call_of_cthulhu
#'
#' @format A character vector with 1,030 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_call_of_cthulhu"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Case Of Charles Dexter Ward"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Case Of Charles Dexter Ward"
#'
#' @examples
#' data("the_case_of_charles_dexter_ward")
#' lovecraftr::the_case_of_charles_dexter_ward
#'
#' @format A character vector with 4,358 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_case_of_charles_dexter_ward"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Cats Of Ulthar"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Cats Of Ulthar"
#'
#' @examples
#' data("the_cats_of_ulthar")
#' lovecraftr::the_cats_of_ulthar
#'
#' @format A character vector with 109 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_cats_of_ulthar"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Colour Out Of Space"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Colour Out Of Space"
#'
#' @examples
#' data("the_colour_out_of_space")
#' lovecraftr::the_colour_out_of_space
#'
#' @format A character vector with 967 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_colour_out_of_space"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Crawling Chaos"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Crawling Chaos"
#'
#' @examples
#' data("the_crawling_chaos")
#' lovecraftr::the_crawling_chaos
#'
#' @format A character vector with 234 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_crawling_chaos"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Descendant"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Descendant"
#'
#' @examples
#' data("the_descendent")
#' lovecraftr::the_descendent
#'
#' @format A character vector with 121 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_descendent"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Doom That Came To Sarnath"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Doom That Came To Sarnath"
#'
#' @examples
#' data("the_doom_that_came_to_sarnath")
#' lovecraftr::the_doom_that_came_to_sarnath
#'
#' @format A character vector with 218 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_doom_that_came_to_sarnath"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Dream Quest Of Unknown Kadath"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Dream Quest Of Unknown Kadath"
#'
#' @examples
#' data("the_dream_quest_of_unknown_kadath")
#' lovecraftr::the_dream_quest_of_unknown_kadath
#'
#' @format A character vector with 3,475 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_dream_quest_of_unknown_kadath"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Dunwich Horror"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Dunwich Horror"
#'
#' @examples
#' data("the_dunwich_horror")
#' lovecraftr::the_dunwich_horror
#'
#' @format A character vector with 1,533 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_dunwich_horror"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Evil Clergyman"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Evil Clergyman"
#'
#' @examples
#' data("the_evil_clergyman")
#' lovecraftr::the_evil_clergyman
#'
#' @format A character vector with 147 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_evil_clergyman"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Festival"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Festival"
#'
#' @examples
#' data("the_festival")
#' lovecraftr::the_festival
#'
#' @format A character vector with 303 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_festival"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Haunter Of The Dark"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Haunter Of The Dark"
#'
#' @examples
#' data("the_haunter_of_the_dark")
#' lovecraftr::the_haunter_of_the_dark
#'
#' @format A character vector with 828 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_haunter_of_the_dark"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Horror At Martin's Beach"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Horror At Martin's Beach"
#'
#' @examples
#' data("the_horror_at_martins_beach")
#' lovecraftr::the_horror_at_martins_beach
#'
#' @format A character vector with 225 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_horror_at_martins_beach"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Horror At Red Hook"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Horror At Red Hook"
#'
#' @examples
#' data("the_horror_at_redhook")
#' lovecraftr::the_horror_at_redhook
#'
#' @format A character vector with 702 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_horror_at_redhook"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Hound"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Hound"
#'
#' @examples
#' data("the_hound")
#' lovecraftr::the_hound
#'
#' @format A character vector with 266 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_hound"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Lurking Fear"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Lurking Fear"
#'
#' @examples
#' data("the_lurking_fear")
#' lovecraftr::the_lurking_fear
#'
#' @format A character vector with 656 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_lurking_fear"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Moon Bog"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Moon Bog"
#'
#' @examples
#' data("the_moon_bog")
#' lovecraftr::the_moon_bog
#'
#' @format A character vector with 266 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_moon_bog"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Music Of Erich Zann"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Music Of Erich Zann"
#'
#' @examples
#' data("the_music_of_erich_zann")
#' lovecraftr::the_music_of_erich_zann
#'
#' @format A character vector with 285 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_music_of_erich_zann"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Nameless City"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Nameless City"
#'
#' @examples
#' data("the_nameless_city")
#' lovecraftr::the_nameless_city
#'
#' @format A character vector with 418 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_nameless_city"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Other Gods"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Other Gods"
#'
#' @examples
#' data("the_other_gods")
#' lovecraftr::the_other_gods
#'
#' @format A character vector with 160 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_other_gods"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Outsider"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Outsider"
#'
#' @examples
#' data("the_outsider")
#' lovecraftr::the_outsider
#'
#' @format A character vector with 213 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_outsider"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Picture In The House"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Picture In The House"
#'
#' @examples
#' data("the_picture_in_the_house")
#' lovecraftr::the_picture_in_the_house
#'
#' @format A character vector with 263 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_picture_in_the_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Quest Of Iranon"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Quest Of Iranon"
#'
#' @examples
#' data("the_quest_of_iranon")
#' lovecraftr::the_quest_of_iranon
#'
#' @format A character vector with 215 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_quest_of_iranon"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Rats In The Walls"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Rats In The Walls"
#'
#' @examples
#' data("the_rats_in_the_walls")
#' lovecraftr::the_rats_in_the_walls
#'
#' @format A character vector with 691 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_rats_in_the_walls"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Shadow Out Of Time"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Shadow Out Of Time"
#'
#' @examples
#' data("the_shadow_out_of_time")
#' lovecraftr::the_shadow_out_of_time
#'
#' @format A character vector with 2,529 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_shadow_out_of_time"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Shadow Over Innsmouth"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Shadow Over Innsmouth"
#'
#' @examples
#' data("the_shadow_over_innsmouth")
#' lovecraftr::the_shadow_over_innsmouth
#'
#' @format A character vector with 2,318 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_shadow_over_innsmouth"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Shunned House"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Shunned House"
#'
#' @examples
#' data("the_shunned_house")
#' lovecraftr::the_shunned_house
#'
#' @format A character vector with 916 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_shunned_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Silver Key"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Silver Key"
#'
#' @examples
#' data("the_silver_key")
#' lovecraftr::the_silver_key
#'
#' @format A character vector with 404 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_silver_key"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Statement Of Randolph Carter"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Statement Of Randolph Carter"
#'
#' @examples
#' data("the_statement_of_randolph_carter")
#' lovecraftr::the_statement_of_randolph_carter
#'
#' @format A character vector with 221 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_statement_of_randolph_carter"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Strange High House In The Mist"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Strange High House In The Mist"
#'
#' @examples
#' data("the_strange_high_house_in_the_mist")
#' lovecraftr::the_strange_high_house_in_the_mist
#'
#' @format A character vector with 289 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_strange_high_house_in_the_mist"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Street"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Street"
#'
#' @examples
#' data("the_street")
#' lovecraftr::the_street
#'
#' @format A character vector with 183 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_street"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Temple"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Temple"
#'
#' @examples
#' data("the_temple")
#' lovecraftr::the_temple
#'
#' @format A character vector with 450 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_temple"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Terrible Old Man"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Terrible Old Man"
#'
#' @examples
#' data("the_terrible_old_man")
#' lovecraftr::the_terrible_old_man
#'
#' @format A character vector with 87 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_terrible_old_man"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Thing On The Doorstep"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Thing On The Doorstep"
#'
#' @examples
#' data("the_thing_on_the_doorstep")
#' lovecraftr::the_thing_on_the_doorstep
#'
#' @format A character vector with 931 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_thing_on_the_doorstep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Tomb"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Tomb"
#'
#' @examples
#' data("the_tomb")
#' lovecraftr::the_tomb
#'
#' @format A character vector with 366 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_tomb"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Transition Of Juan Romero"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Transition Of Juan Romero"
#'
#' @examples
#' data("the_transition_of_juan_romero")
#' lovecraftr::the_transition_of_juan_romero
#'
#' @format A character vector with 234 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_transition_of_juan_romero"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Tree"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Tree"
#'
#' @examples
#' data("the_tree")
#' lovecraftr::the_tree
#'
#' @format A character vector with 127 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_tree"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Unnamable"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Unnamable"
#'
#' @examples
#' data("the_unnamable")
#' lovecraftr::the_unnamable
#'
#' @format A character vector with 239 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_unnamable"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Very Old Folk"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Very Old Folk"
#'
#' @examples
#' data("the_very_old_folk")
#' lovecraftr::the_very_old_folk
#'
#' @format A character vector with 210 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_very_old_folk"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The Whisperer In Darkness"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The Whisperer In Darkness"
#'
#' @examples
#' data("the_whisperer_in_darkness")
#' lovecraftr::the_whisperer_in_darkness
#'
#' @format A character vector with 2,303 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_whisperer_in_darkness"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "The White Ship"
#'
#' @description A dataset containing text of H. P. Lovecraft's "The White Ship"
#'
#' @examples
#' data("the_white_ship")
#' lovecraftr::the_white_ship
#'
#' @format A character vector with 200 elements, with roughly 80 characters per line
#'
#' @source Public domain
"the_white_ship"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "Through The Gates Of The Silver Key"
#'
#' @description A dataset containing text of H. P. Lovecraft's "Through The Gates Of The Silver Key"
#'
#' @examples
#' data("through_the_gates_of_the_silver_key")
#' lovecraftr::through_the_gates_of_the_silver_key
#'
#' @format A character vector with 1,305 elements, with roughly 80 characters per line
#'
#' @source Public domain
"through_the_gates_of_the_silver_key"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "What The Moon Brings"
#'
#' @description A dataset containing text of H. P. Lovecraft's "What The Moon Brings"
#'
#' @examples
#' data("what_the_moon_brings")
#' lovecraftr::what_the_moon_brings
#'
#' @format A character vector with 60 elements, with roughly 80 characters per line
#'
#' @source Public domain
"what_the_moon_brings"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of Lovecraft's corpus
#'
#' @description A dataset containing text of all the H. P. Lovecraft works available in {lovecraftr}
#'
#' @examples
#' data("lovecraft")
#' lovecraftr::lovecraft
#' df <- lovecraftr::lovecraft_corpus()
#'
#' @format A tibble with 43,347 rows and 2 columns:
#' \describe{
#'   \item{title}{Title of the work}
#'   \item{text}{~80 characters of text from the title}
#' }
#'
#' @source Public domain
"lovecraft"
