# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title _At the Mountains of Madness_
#' @description A dataset containing text of H. P. Lovecraft's _At the Mountains of Madness_.
#' @usage data(at_the_mountains_of_madness)
#' @format A character vector with 3,579 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets novella
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/at_the_mountains_of_madness)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/at_the_mountains_of_madness.rda).
#' @md
"at_the_mountains_of_madness"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Azathoth"
#' @description A dataset containing text of H. P. Lovecraft's "Azathoth".
#' @usage data(azathoth)
#' @format A character vector with 37 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/azathoth)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/azathoth.rda).
#' @md
"azathoth"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Beyond the Wall of Sleep"
#' @description A dataset containing text of H. P. Lovecraft's "Beyond the Wall of Sleep".
#' @usage data(beyond_the_wall_of_sleep)
#' @format A character vector with 361 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/beyond_the_wall_of_sleep)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/beyond_the_wall_of_sleep.rda).
#' @md
"beyond_the_wall_of_sleep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Celephais"
#' @description A dataset containing text of H. P. Lovecraft's "Celephais".
#' @usage data(celephais)
#' @format A character vector with 202 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/celephais)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/celephais.rda).
#' @md
"celephais"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Cool Air"
#' @description A dataset containing text of H. P. Lovecraft's "Cool Air".
#' @usage data(cool_air)
#' @format A character vector with 292 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/cool_air)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/cool_air.rda).
#' @md
"cool_air"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Dagon"
#' @description A dataset containing text of H. P. Lovecraft's "Dagon".
#' @usage data(dagon)
#' @format A character vector with 187 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/dagon)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/dagon.rda).
#' @md
"dagon"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Dreams in the Witch-House"
#' @description A dataset containing text of H. P. Lovecraft's "Dreams in the Witch-House".
#' @usage data(dreams_in_the_witch_house)
#' @format A character vector with 1,271 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/dreams_in_the_witch_house)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/dreams_in_the_witch_house.rda).
#' @md
"dreams_in_the_witch_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Ex Oblivione"
#' @description A dataset containing text of H. P. Lovecraft's "Ex Oblivione".
#' @usage data(ex_oblivione)
#' @format A character vector with 66 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/ex_oblivione)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/ex_oblivione.rda).
#' @md
"ex_oblivione"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Facts Concerning the Late Arthur Jermyn and His Family"
#' @description A dataset containing text of H. P. Lovecraft's "Facts Concerning the Late Arthur Jermyn and His Family".
#' @usage data(facts_concerning_the_late_arthur_jermyn_and_his_family)
#' @format A character vector with 303 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/facts_concerning_the_late_arthur_jermyn_and_his_family)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/facts_concerning_the_late_arthur_jermyn_and_his_family.rda).
#' @md
"facts_concerning_the_late_arthur_jermyn_and_his_family"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "From Beyond"
#' @description A dataset containing text of H. P. Lovecraft's "From Beyond".
#' @usage data(from_beyond)
#' @format A character vector with 222 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/from_beyond)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/from_beyond.rda).
#' @md
"from_beyond"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "He"
#' @description A dataset containing text of H. P. Lovecraft's "He".
#' @usage data(he)
#' @format A character vector with 360 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/he)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/he.rda).
#' @md
"he"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Herbert West: Reanimator"
#' @description A dataset containing text of H. P. Lovecraft's "Herbert West: Reanimator".
#' @usage data(herbert_west_reanimator)
#' @format A character vector with 1,053 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/herbert_west_reanimator)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/herbert_west_reanimator.rda).
#' @md
"herbert_west_reanimator"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Hypnos"
#' @description A dataset containing text of H. P. Lovecraft's "Hypnos".
#' @usage data(hypnos)
#' @format A character vector with 233 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/hypnos)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/hypnos.rda).
#' @md
"hypnos"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Imprisoned with the Pharaohs"
#' @description A dataset containing text of H. P. Lovecraft's "Imprisoned with the Pharaohs".
#' @usage data(imprisoned_with_the_pharoahs)
#' @format A character vector with 948 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/imprisoned_with_the_pharoahs)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/imprisoned_with_the_pharoahs.rda).
#' @md
"imprisoned_with_the_pharoahs"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "In the Vault"
#' @description A dataset containing text of H. P. Lovecraft's "In the Vault".
#' @usage data(in_the_vault)
#' @format A character vector with 272 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/in_the_vault)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/in_the_vault.rda).
#' @md
"in_the_vault"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Medusa's Coil"
#' @description A dataset containing text of H. P. Lovecraft's "Medusa's Coil".
#' @usage data(medusas_coil)
#' @format A character vector with 1,443 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/medusas_coil)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/medusas_coil.rda).
#' @md
"medusas_coil"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Memory"
#' @description A dataset containing text of H. P. Lovecraft's "Memory".
#' @usage data(memory)
#' @format A character vector with 31 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/memory)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/memory.rda).
#' @md
"memory"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Nyarlathotep"
#' @description A dataset containing text of H. P. Lovecraft's "Nyarlathotep".
#' @usage data(nyarlathotep)
#' @format A character vector with 97 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/nyarlathotep)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/nyarlathotep.rda).
#' @md
"nyarlathotep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Pickman's Model"
#' @description A dataset containing text of H. P. Lovecraft's "Pickman's Model".
#' @usage data(pickmans_model)
#' @format A character vector with 455 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/pickmans_model)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/pickmans_model.rda).
#' @md
"pickmans_model"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Poetry of the Gods"
#' @description A dataset containing text of H. P. Lovecraft's "Poetry of the Gods".
#' @usage data(poetry_of_the_gods)
#' @format A character vector with 157 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/poetry_of_the_gods)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/poetry_of_the_gods.rda).
#' @md
"poetry_of_the_gods"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Polaris"
#' @description A dataset containing text of H. P. Lovecraft's "Polaris".
#' @usage data(polaris)
#' @format A character vector with 129 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/polaris)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/polaris.rda).
#' @md
"polaris"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Alchemist"
#' @description A dataset containing text of H. P. Lovecraft's "The Alchemist".
#' @usage data(the_alchemist)
#' @format A character vector with 295 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_alchemist)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_alchemist.rda).
#' @md
"the_alchemist"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Beast in the Cave"
#' @description A dataset containing text of H. P. Lovecraft's "The Beast in the Cave".
#' @usage data(the_beast_in_the_cave)
#' @format A character vector with 204 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_beast_in_the_cave)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_beast_in_the_cave.rda).
#' @md
"the_beast_in_the_cave"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Book"
#' @description A dataset containing text of H. P. Lovecraft's "The Book".
#' @usage data(the_book)
#' @format A character vector with 95 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_book)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_book.rda).
#' @md
"the_book"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Call of Cthulhu"
#' @description A dataset containing text of H. P. Lovecraft's "The Call of Cthulhu".
#' @usage data(the_call_of_cthulhu)
#' @format A character vector with 1,030 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_call_of_cthulhu)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_call_of_cthulhu.rda).
#' @md
"the_call_of_cthulhu"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title _The Case of Charles Dexter Ward_
#' @description A dataset containing text of H. P. Lovecraft's _The Case of Charles Dexter Ward_.
#' @usage data(the_case_of_charles_dexter_ward)
#' @format A character vector with 4,358 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets novella
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_case_of_charles_dexter_ward)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_case_of_charles_dexter_ward.rda).
#' @md
"the_case_of_charles_dexter_ward"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Cats of Ulthar"
#' @description A dataset containing text of H. P. Lovecraft's "The Cats of Ulthar".
#' @usage data(the_cats_of_ulthar)
#' @format A character vector with 109 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_cats_of_ulthar)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_cats_of_ulthar.rda).
#' @md
"the_cats_of_ulthar"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Colour Out of Space"
#' @description A dataset containing text of H. P. Lovecraft's "The Colour Out of Space".
#' @usage data(the_colour_out_of_space)
#' @format A character vector with 967 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_colour_out_of_space)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_colour_out_of_space.rda).
#' @md
"the_colour_out_of_space"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Crawling Chaos"
#' @description A dataset containing text of H. P. Lovecraft's "The Crawling Chaos".
#' @usage data(the_crawling_chaos)
#' @format A character vector with 234 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_crawling_chaos)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_crawling_chaos.rda).
#' @md
"the_crawling_chaos"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Descendant"
#' @description A dataset containing text of H. P. Lovecraft's "The Descendant".
#' @usage data(the_descendent)
#' @format A character vector with 121 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_descendent)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_descendent.rda).
#' @md
"the_descendent"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Doom that Came to Sarnath"
#' @description A dataset containing text of H. P. Lovecraft's "The Doom that Came to Sarnath".
#' @usage data(the_doom_that_came_to_sarnath)
#' @format A character vector with 218 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_doom_that_came_to_sarnath)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_doom_that_came_to_sarnath.rda).
#' @md
"the_doom_that_came_to_sarnath"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title _The Dream Quest of Unknown Kadath_
#' @description A dataset containing text of H. P. Lovecraft's _The Dream Quest of Unknown Kadath_.
#' @usage data(the_dream_quest_of_unknown_kadath)
#' @format A character vector with 3,475 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets novella
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_dream_quest_of_unknown_kadath)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_dream_quest_of_unknown_kadath.rda).
#' @md
"the_dream_quest_of_unknown_kadath"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title _The Dunwich Horror_
#' @description A dataset containing text of H. P. Lovecraft's _The Dunwich Horror_.
#' @usage data(the_dunwich_horror)
#' @format A character vector with 1,533 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets novella
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_dunwich_horror)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_dunwich_horror.rda).
#' @md
"the_dunwich_horror"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Evil Clergyman"
#' @description A dataset containing text of H. P. Lovecraft's "The Evil Clergyman".
#' @usage data(the_evil_clergyman)
#' @format A character vector with 147 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_evil_clergyman)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_evil_clergyman.rda).
#' @md
"the_evil_clergyman"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Festival"
#' @description A dataset containing text of H. P. Lovecraft's "The Festival".
#' @usage data(the_festival)
#' @format A character vector with 303 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_festival)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_festival.rda).
#' @md
"the_festival"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Haunter of the Dark"
#' @description A dataset containing text of H. P. Lovecraft's "The Haunter of the Dark".
#' @usage data(the_haunter_of_the_dark)
#' @format A character vector with 828 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_haunter_of_the_dark)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_haunter_of_the_dark.rda).
#' @md
"the_haunter_of_the_dark"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Horror at Martin's Beach"
#' @description A dataset containing text of H. P. Lovecraft's "The Horror at Martin's Beach".
#' @usage data(the_horror_at_martins_beach)
#' @format A character vector with 225 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_horror_at_martins_beach)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_horror_at_martins_beach.rda).
#' @md
"the_horror_at_martins_beach"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Horror at Red Hook"
#' @description A dataset containing text of H. P. Lovecraft's "The Horror at Red Hook".
#' @usage data(the_horror_at_redhook)
#' @format A character vector with 702 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_horror_at_redhook)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_horror_at_redhook.rda).
#' @md
"the_horror_at_redhook"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Hound"
#' @description A dataset containing text of H. P. Lovecraft's "The Hound".
#' @usage data(the_hound)
#' @format A character vector with 266 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_hound)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_hound.rda).
#' @md
"the_hound"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Lurking Fear"
#' @description A dataset containing text of H. P. Lovecraft's "The Lurking Fear".
#' @usage data(the_lurking_fear)
#' @format A character vector with 656 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_lurking_fear)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_lurking_fear.rda).
#' @md
"the_lurking_fear"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Moon Bog"
#' @description A dataset containing text of H. P. Lovecraft's "The Moon Bog".
#' @usage data(the_moon_bog)
#' @format A character vector with 266 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_moon_bog)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_moon_bog.rda).
#' @md
"the_moon_bog"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Music of Erich Zann"
#' @description A dataset containing text of H. P. Lovecraft's "The Music of Erich Zann".
#' @usage data(the_music_of_erich_zann)
#' @format A character vector with 285 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_music_of_erich_zann)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_music_of_erich_zann.rda).
#' @md
"the_music_of_erich_zann"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Nameless City"
#' @description A dataset containing text of H. P. Lovecraft's "The Nameless City".
#' @usage data(the_nameless_city)
#' @format A character vector with 418 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_nameless_city)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_nameless_city.rda).
#' @md
"the_nameless_city"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Other Gods"
#' @description A dataset containing text of H. P. Lovecraft's "The Other Gods".
#' @usage data(the_other_gods)
#' @format A character vector with 160 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_other_gods)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_other_gods.rda).
#' @md
"the_other_gods"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Outsider"
#' @description A dataset containing text of H. P. Lovecraft's "The Outsider".
#' @usage data(the_outsider)
#' @format A character vector with 213 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_outsider)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_outsider.rda).
#' @md
"the_outsider"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Picture in the House"
#' @description A dataset containing text of H. P. Lovecraft's "The Picture in the House".
#' @usage data(the_picture_in_the_house)
#' @format A character vector with 263 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_picture_in_the_house)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_picture_in_the_house.rda).
#' @md
"the_picture_in_the_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Quest of Iranon"
#' @description A dataset containing text of H. P. Lovecraft's "The Quest of Iranon".
#' @usage data(the_quest_of_iranon)
#' @format A character vector with 215 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_quest_of_iranon)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_quest_of_iranon.rda).
#' @md
"the_quest_of_iranon"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Rats in the Walls"
#' @description A dataset containing text of H. P. Lovecraft's "The Rats in the Walls".
#' @usage data(the_rats_in_the_walls)
#' @format A character vector with 691 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_rats_in_the_walls)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_rats_in_the_walls.rda).
#' @md
"the_rats_in_the_walls"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title _The Shadow Out of Time_
#' @description A dataset containing text of H. P. Lovecraft's _The Shadow Out of Time_.
#' @usage data(the_shadow_out_of_time)
#' @format A character vector with 2,529 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets novella
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_shadow_out_of_time)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_shadow_out_of_time.rda).
#' @md
"the_shadow_out_of_time"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title _The Shadow Over Innsmouth_
#' @description A dataset containing text of H. P. Lovecraft's _The Shadow Over Innsmouth_.
#' @usage data(the_shadow_over_innsmouth)
#' @format A character vector with 2,318 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets novella
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_shadow_over_innsmouth)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_shadow_over_innsmouth.rda).
#' @md
"the_shadow_over_innsmouth"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Shunned House"
#' @description A dataset containing text of H. P. Lovecraft's "The Shunned House".
#' @usage data(the_shunned_house)
#' @format A character vector with 916 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_shunned_house)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_shunned_house.rda).
#' @md
"the_shunned_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Silver Key"
#' @description A dataset containing text of H. P. Lovecraft's "The Silver Key".
#' @usage data(the_silver_key)
#' @format A character vector with 404 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_silver_key)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_silver_key.rda).
#' @md
"the_silver_key"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Statement of Randolph Carter"
#' @description A dataset containing text of H. P. Lovecraft's "The Statement of Randolph Carter".
#' @usage data(the_statement_of_randolph_carter)
#' @format A character vector with 221 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_statement_of_randolph_carter)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_statement_of_randolph_carter.rda).
#' @md
"the_statement_of_randolph_carter"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Strange High House in the Mist"
#' @description A dataset containing text of H. P. Lovecraft's "The Strange High House in the Mist".
#' @usage data(the_strange_high_house_in_the_mist)
#' @format A character vector with 289 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_strange_high_house_in_the_mist)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_strange_high_house_in_the_mist.rda).
#' @md
"the_strange_high_house_in_the_mist"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Street"
#' @description A dataset containing text of H. P. Lovecraft's "The Street".
#' @usage data(the_street)
#' @format A character vector with 183 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_street)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_street.rda).
#' @md
"the_street"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Temple"
#' @description A dataset containing text of H. P. Lovecraft's "The Temple".
#' @usage data(the_temple)
#' @format A character vector with 450 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_temple)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_temple.rda).
#' @md
"the_temple"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Terrible Old Man"
#' @description A dataset containing text of H. P. Lovecraft's "The Terrible Old Man".
#' @usage data(the_terrible_old_man)
#' @format A character vector with 87 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_terrible_old_man)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_terrible_old_man.rda).
#' @md
"the_terrible_old_man"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Thing on the Doorstep"
#' @description A dataset containing text of H. P. Lovecraft's "The Thing on the Doorstep".
#' @usage data(the_thing_on_the_doorstep)
#' @format A character vector with 931 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_thing_on_the_doorstep)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_thing_on_the_doorstep.rda).
#' @md
"the_thing_on_the_doorstep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Tomb"
#' @description A dataset containing text of H. P. Lovecraft's "The Tomb".
#' @usage data(the_tomb)
#' @format A character vector with 366 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_tomb)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_tomb.rda).
#' @md
"the_tomb"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Transition of Juan Romero"
#' @description A dataset containing text of H. P. Lovecraft's "The Transition of Juan Romero".
#' @usage data(the_transition_of_juan_romero)
#' @format A character vector with 234 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_transition_of_juan_romero)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_transition_of_juan_romero.rda).
#' @md
"the_transition_of_juan_romero"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Tree"
#' @description A dataset containing text of H. P. Lovecraft's "The Tree".
#' @usage data(the_tree)
#' @format A character vector with 127 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_tree)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_tree.rda).
#' @md
"the_tree"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Unnamable"
#' @description A dataset containing text of H. P. Lovecraft's "The Unnamable".
#' @usage data(the_unnamable)
#' @format A character vector with 239 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_unnamable)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_unnamable.rda).
#' @md
"the_unnamable"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The Very Old Folk"
#' @description A dataset containing text of H. P. Lovecraft's "The Very Old Folk".
#' @usage data(the_very_old_folk)
#' @format A character vector with 210 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_very_old_folk)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_very_old_folk.rda).
#' @md
"the_very_old_folk"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title _The Whisperer in Darkness_
#' @description A dataset containing text of H. P. Lovecraft's _The Whisperer in Darkness_.
#' @usage data(the_whisperer_in_darkness)
#' @format A character vector with 2,303 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets novella
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_whisperer_in_darkness)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_whisperer_in_darkness.rda).
#' @md
"the_whisperer_in_darkness"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "The White Ship"
#' @description A dataset containing text of H. P. Lovecraft's "The White Ship".
#' @usage data(the_white_ship)
#' @format A character vector with 200 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_white_ship)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_white_ship.rda).
#' @md
"the_white_ship"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "Through the Gates of the Silver Key"
#' @description A dataset containing text of H. P. Lovecraft's "Through the Gates of the Silver Key".
#' @usage data(through_the_gates_of_the_silver_key)
#' @format A character vector with 1,305 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/through_the_gates_of_the_silver_key)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/through_the_gates_of_the_silver_key.rda).
#' @md
"through_the_gates_of_the_silver_key"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title "What the Moon Brings"
#' @description A dataset containing text of H. P. Lovecraft's "What the Moon Brings".
#' @usage data(what_the_moon_brings)
#' @format A character vector with 60 elements, with roughly 80 characters per line.
#' @docType data
#' @keywords datasets short
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/what_the_moon_brings)
#'   or download the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/what_the_moon_brings.rda).
#' @md
"what_the_moon_brings"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of Lovecraft's Corpus
#' @description A dataset containing text of all the H. P. Lovecraft works available in this package.
#' @usage data(lovecraft)
#' @format A tibble with 43,347 rows and 2 columns:
#' \describe{
#'   \item{title}{Title of the work}
#'   \item{text}{~80 characters of text from the title}
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#' @md
"lovecraft"
