# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "AT THE MOUNTAINS OF MADNESS"
#' @description A dataset containing text of H. P. Lovecraft's "AT THE MOUNTAINS OF MADNESS"
#' @usage data(at_the_mountains_of_madness)
#' @format A character vector with 3,579 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(at_the_mountains_of_madness)
#'
#' at_the_mountains_of_madness <- lovecraftr::at_the_mountains_of_madness
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/at_the_mountains_of_madness) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/at_the_mountains_of_madness.rda) to use with R.
#' @md
"at_the_mountains_of_madness"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "AZATHOTH"
#' @description A dataset containing text of H. P. Lovecraft's "AZATHOTH"
#' @usage data(azathoth)
#' @format A character vector with 37 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(azathoth)
#'
#' azathoth <- lovecraftr::azathoth
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/azathoth) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/azathoth.rda) to use with R.
#' @md
"azathoth"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "BEYOND THE WALL OF SLEEP"
#' @description A dataset containing text of H. P. Lovecraft's "BEYOND THE WALL OF SLEEP"
#' @usage data(beyond_the_wall_of_sleep)
#' @format A character vector with 361 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(beyond_the_wall_of_sleep)
#'
#' beyond_the_wall_of_sleep <- lovecraftr::beyond_the_wall_of_sleep
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/beyond_the_wall_of_sleep) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/beyond_the_wall_of_sleep.rda) to use with R.
#' @md
"beyond_the_wall_of_sleep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "CELEPHAIS"
#' @description A dataset containing text of H. P. Lovecraft's "CELEPHAIS"
#' @usage data(celephais)
#' @format A character vector with 202 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(celephais)
#'
#' celephais <- lovecraftr::celephais
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/celephais) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/celephais.rda) to use with R.
#' @md
"celephais"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "COOL AIR"
#' @description A dataset containing text of H. P. Lovecraft's "COOL AIR"
#' @usage data(cool_air)
#' @format A character vector with 292 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(cool_air)
#'
#' cool_air <- lovecraftr::cool_air
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/cool_air) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/cool_air.rda) to use with R.
#' @md
"cool_air"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "DAGON"
#' @description A dataset containing text of H. P. Lovecraft's "DAGON"
#' @usage data(dagon)
#' @format A character vector with 187 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(dagon)
#'
#' dagon <- lovecraftr::dagon
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/dagon) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/dagon.rda) to use with R.
#' @md
"dagon"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "DREAMS IN THE WITCH-HOUSE"
#' @description A dataset containing text of H. P. Lovecraft's "DREAMS IN THE WITCH-HOUSE"
#' @usage data(dreams_in_the_witch_house)
#' @format A character vector with 1,271 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(dreams_in_the_witch_house)
#'
#' dreams_in_the_witch_house <- lovecraftr::dreams_in_the_witch_house
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/dreams_in_the_witch_house) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/dreams_in_the_witch_house.rda) to use with R.
#' @md
"dreams_in_the_witch_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "EX OBLIVIONE"
#' @description A dataset containing text of H. P. Lovecraft's "EX OBLIVIONE"
#' @usage data(ex_oblivione)
#' @format A character vector with 66 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(ex_oblivione)
#'
#' ex_oblivione <- lovecraftr::ex_oblivione
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/ex_oblivione) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/ex_oblivione.rda) to use with R.
#' @md
"ex_oblivione"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "FACTS CONCERNING THE LATE ARTHUR JERMYN AND HIS FAMILY"
#' @description A dataset containing text of H. P. Lovecraft's "FACTS CONCERNING THE LATE ARTHUR JERMYN AND HIS FAMILY"
#' @usage data(facts_concerning_the_late_arthur_jermyn_and_his_family)
#' @format A character vector with 303 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(facts_concerning_the_late_arthur_jermyn_and_his_family)
#'
#' facts_concerning_the_late_arthur_jermyn_and_his_family <- lovecraftr::facts_concerning_the_late_arthur_jermyn_and_his_family
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/facts_concerning_the_late_arthur_jermyn_and_his_family) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/facts_concerning_the_late_arthur_jermyn_and_his_family.rda) to use with R.
#' @md
"facts_concerning_the_late_arthur_jermyn_and_his_family"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "FROM BEYOND"
#' @description A dataset containing text of H. P. Lovecraft's "FROM BEYOND"
#' @usage data(from_beyond)
#' @format A character vector with 222 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(from_beyond)
#'
#' from_beyond <- lovecraftr::from_beyond
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/from_beyond) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/from_beyond.rda) to use with R.
#' @md
"from_beyond"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "HE"
#' @description A dataset containing text of H. P. Lovecraft's "HE"
#' @usage data(he)
#' @format A character vector with 360 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(he)
#'
#' he <- lovecraftr::he
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/he) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/he.rda) to use with R.
#' @md
"he"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "HERBERT WEST: REANIMATOR"
#' @description A dataset containing text of H. P. Lovecraft's "HERBERT WEST: REANIMATOR"
#' @usage data(herbert_west_reanimator)
#' @format A character vector with 1,053 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(herbert_west_reanimator)
#'
#' herbert_west_reanimator <- lovecraftr::herbert_west_reanimator
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/herbert_west_reanimator) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/herbert_west_reanimator.rda) to use with R.
#' @md
"herbert_west_reanimator"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "HYPNOS"
#' @description A dataset containing text of H. P. Lovecraft's "HYPNOS"
#' @usage data(hypnos)
#' @format A character vector with 233 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(hypnos)
#'
#' hypnos <- lovecraftr::hypnos
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/hypnos) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/hypnos.rda) to use with R.
#' @md
"hypnos"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "IMPRISONED WITH THE PHARAOHS"
#' @description A dataset containing text of H. P. Lovecraft's "IMPRISONED WITH THE PHARAOHS"
#' @usage data(imprisoned_with_the_pharoahs)
#' @format A character vector with 948 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(imprisoned_with_the_pharoahs)
#'
#' imprisoned_with_the_pharoahs <- lovecraftr::imprisoned_with_the_pharoahs
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/imprisoned_with_the_pharoahs) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/imprisoned_with_the_pharoahs.rda) to use with R.
#' @md
"imprisoned_with_the_pharoahs"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "IN THE VAULT"
#' @description A dataset containing text of H. P. Lovecraft's "IN THE VAULT"
#' @usage data(in_the_vault)
#' @format A character vector with 272 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(in_the_vault)
#'
#' in_the_vault <- lovecraftr::in_the_vault
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/in_the_vault) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/in_the_vault.rda) to use with R.
#' @md
"in_the_vault"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "MEDUSA'S COIL"
#' @description A dataset containing text of H. P. Lovecraft's "MEDUSA'S COIL"
#' @usage data(medusas_coil)
#' @format A character vector with 1,443 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(medusas_coil)
#'
#' medusas_coil <- lovecraftr::medusas_coil
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/medusas_coil) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/medusas_coil.rda) to use with R.
#' @md
"medusas_coil"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "MEMORY"
#' @description A dataset containing text of H. P. Lovecraft's "MEMORY"
#' @usage data(memory)
#' @format A character vector with 31 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(memory)
#'
#' memory <- lovecraftr::memory
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/memory) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/memory.rda) to use with R.
#' @md
"memory"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "NYARLATHOTEP"
#' @description A dataset containing text of H. P. Lovecraft's "NYARLATHOTEP"
#' @usage data(nyarlathotep)
#' @format A character vector with 97 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(nyarlathotep)
#'
#' nyarlathotep <- lovecraftr::nyarlathotep
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/nyarlathotep) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/nyarlathotep.rda) to use with R.
#' @md
"nyarlathotep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "PICKMAN'S MODEL"
#' @description A dataset containing text of H. P. Lovecraft's "PICKMAN'S MODEL"
#' @usage data(pickmans_model)
#' @format A character vector with 455 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(pickmans_model)
#'
#' pickmans_model <- lovecraftr::pickmans_model
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/pickmans_model) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/pickmans_model.rda) to use with R.
#' @md
"pickmans_model"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "POETRY OF THE GODS"
#' @description A dataset containing text of H. P. Lovecraft's "POETRY OF THE GODS"
#' @usage data(poetry_of_the_gods)
#' @format A character vector with 157 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(poetry_of_the_gods)
#'
#' poetry_of_the_gods <- lovecraftr::poetry_of_the_gods
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/poetry_of_the_gods) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/poetry_of_the_gods.rda) to use with R.
#' @md
"poetry_of_the_gods"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "POLARIS"
#' @description A dataset containing text of H. P. Lovecraft's "POLARIS"
#' @usage data(polaris)
#' @format A character vector with 129 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(polaris)
#'
#' polaris <- lovecraftr::polaris
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/polaris) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/polaris.rda) to use with R.
#' @md
"polaris"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE ALCHEMIST"
#' @description A dataset containing text of H. P. Lovecraft's "THE ALCHEMIST"
#' @usage data(the_alchemist)
#' @format A character vector with 295 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_alchemist)
#'
#' the_alchemist <- lovecraftr::the_alchemist
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_alchemist) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_alchemist.rda) to use with R.
#' @md
"the_alchemist"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE BEAST IN THE CAVE"
#' @description A dataset containing text of H. P. Lovecraft's "THE BEAST IN THE CAVE"
#' @usage data(the_beast_in_the_cave)
#' @format A character vector with 204 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_beast_in_the_cave)
#'
#' the_beast_in_the_cave <- lovecraftr::the_beast_in_the_cave
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_beast_in_the_cave) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_beast_in_the_cave.rda) to use with R.
#' @md
"the_beast_in_the_cave"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE BOOK"
#' @description A dataset containing text of H. P. Lovecraft's "THE BOOK"
#' @usage data(the_book)
#' @format A character vector with 95 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_book)
#'
#' the_book <- lovecraftr::the_book
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_book) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_book.rda) to use with R.
#' @md
"the_book"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE CALL OF CTHULHU"
#' @description A dataset containing text of H. P. Lovecraft's "THE CALL OF CTHULHU"
#' @usage data(the_call_of_cthulhu)
#' @format A character vector with 1,030 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_call_of_cthulhu)
#'
#' the_call_of_cthulhu <- lovecraftr::the_call_of_cthulhu
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_call_of_cthulhu) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_call_of_cthulhu.rda) to use with R.
#' @md
"the_call_of_cthulhu"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE CASE OF CHARLES DEXTER WARD"
#' @description A dataset containing text of H. P. Lovecraft's "THE CASE OF CHARLES DEXTER WARD"
#' @usage data(the_case_of_charles_dexter_ward)
#' @format A character vector with 4,358 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_case_of_charles_dexter_ward)
#'
#' the_case_of_charles_dexter_ward <- lovecraftr::the_case_of_charles_dexter_ward
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_case_of_charles_dexter_ward) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_case_of_charles_dexter_ward.rda) to use with R.
#' @md
"the_case_of_charles_dexter_ward"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE CATS OF ULTHAR"
#' @description A dataset containing text of H. P. Lovecraft's "THE CATS OF ULTHAR"
#' @usage data(the_cats_of_ulthar)
#' @format A character vector with 109 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_cats_of_ulthar)
#'
#' the_cats_of_ulthar <- lovecraftr::the_cats_of_ulthar
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_cats_of_ulthar) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_cats_of_ulthar.rda) to use with R.
#' @md
"the_cats_of_ulthar"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE COLOUR OUT OF SPACE"
#' @description A dataset containing text of H. P. Lovecraft's "THE COLOUR OUT OF SPACE"
#' @usage data(the_colour_out_of_space)
#' @format A character vector with 967 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_colour_out_of_space)
#'
#' the_colour_out_of_space <- lovecraftr::the_colour_out_of_space
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_colour_out_of_space) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_colour_out_of_space.rda) to use with R.
#' @md
"the_colour_out_of_space"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE CRAWLING CHAOS"
#' @description A dataset containing text of H. P. Lovecraft's "THE CRAWLING CHAOS"
#' @usage data(the_crawling_chaos)
#' @format A character vector with 234 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_crawling_chaos)
#'
#' the_crawling_chaos <- lovecraftr::the_crawling_chaos
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_crawling_chaos) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_crawling_chaos.rda) to use with R.
#' @md
"the_crawling_chaos"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE DESCENDANT"
#' @description A dataset containing text of H. P. Lovecraft's "THE DESCENDANT"
#' @usage data(the_descendent)
#' @format A character vector with 121 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_descendent)
#'
#' the_descendent <- lovecraftr::the_descendent
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_descendent) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_descendent.rda) to use with R.
#' @md
"the_descendent"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE DOOM THAT CAME TO SARNATH"
#' @description A dataset containing text of H. P. Lovecraft's "THE DOOM THAT CAME TO SARNATH"
#' @usage data(the_doom_that_came_to_sarnath)
#' @format A character vector with 218 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_doom_that_came_to_sarnath)
#'
#' the_doom_that_came_to_sarnath <- lovecraftr::the_doom_that_came_to_sarnath
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_doom_that_came_to_sarnath) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_doom_that_came_to_sarnath.rda) to use with R.
#' @md
"the_doom_that_came_to_sarnath"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE DREAM QUEST OF UNKNOWN KADATH"
#' @description A dataset containing text of H. P. Lovecraft's "THE DREAM QUEST OF UNKNOWN KADATH"
#' @usage data(the_dream_quest_of_unknown_kadath)
#' @format A character vector with 3,475 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_dream_quest_of_unknown_kadath)
#'
#' the_dream_quest_of_unknown_kadath <- lovecraftr::the_dream_quest_of_unknown_kadath
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_dream_quest_of_unknown_kadath) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_dream_quest_of_unknown_kadath.rda) to use with R.
#' @md
"the_dream_quest_of_unknown_kadath"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE DUNWICH HORROR"
#' @description A dataset containing text of H. P. Lovecraft's "THE DUNWICH HORROR"
#' @usage data(the_dunwich_horror)
#' @format A character vector with 1,533 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_dunwich_horror)
#'
#' the_dunwich_horror <- lovecraftr::the_dunwich_horror
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_dunwich_horror) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_dunwich_horror.rda) to use with R.
#' @md
"the_dunwich_horror"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE EVIL CLERGYMAN"
#' @description A dataset containing text of H. P. Lovecraft's "THE EVIL CLERGYMAN"
#' @usage data(the_evil_clergyman)
#' @format A character vector with 147 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_evil_clergyman)
#'
#' the_evil_clergyman <- lovecraftr::the_evil_clergyman
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_evil_clergyman) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_evil_clergyman.rda) to use with R.
#' @md
"the_evil_clergyman"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE FESTIVAL"
#' @description A dataset containing text of H. P. Lovecraft's "THE FESTIVAL"
#' @usage data(the_festival)
#' @format A character vector with 303 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_festival)
#'
#' the_festival <- lovecraftr::the_festival
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_festival) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_festival.rda) to use with R.
#' @md
"the_festival"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE HAUNTER OF THE DARK"
#' @description A dataset containing text of H. P. Lovecraft's "THE HAUNTER OF THE DARK"
#' @usage data(the_haunter_of_the_dark)
#' @format A character vector with 828 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_haunter_of_the_dark)
#'
#' the_haunter_of_the_dark <- lovecraftr::the_haunter_of_the_dark
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_haunter_of_the_dark) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_haunter_of_the_dark.rda) to use with R.
#' @md
"the_haunter_of_the_dark"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE HORROR AT MARTIN'S BEACH"
#' @description A dataset containing text of H. P. Lovecraft's "THE HORROR AT MARTIN'S BEACH"
#' @usage data(the_horror_at_martins_beach)
#' @format A character vector with 225 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_horror_at_martins_beach)
#'
#' the_horror_at_martins_beach <- lovecraftr::the_horror_at_martins_beach
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_horror_at_martins_beach) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_horror_at_martins_beach.rda) to use with R.
#' @md
"the_horror_at_martins_beach"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE HORROR AT RED HOOK"
#' @description A dataset containing text of H. P. Lovecraft's "THE HORROR AT RED HOOK"
#' @usage data(the_horror_at_redhook)
#' @format A character vector with 702 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_horror_at_redhook)
#'
#' the_horror_at_redhook <- lovecraftr::the_horror_at_redhook
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_horror_at_redhook) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_horror_at_redhook.rda) to use with R.
#' @md
"the_horror_at_redhook"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE HOUND"
#' @description A dataset containing text of H. P. Lovecraft's "THE HOUND"
#' @usage data(the_hound)
#' @format A character vector with 266 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_hound)
#'
#' the_hound <- lovecraftr::the_hound
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_hound) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_hound.rda) to use with R.
#' @md
"the_hound"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE LURKING FEAR"
#' @description A dataset containing text of H. P. Lovecraft's "THE LURKING FEAR"
#' @usage data(the_lurking_fear)
#' @format A character vector with 656 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_lurking_fear)
#'
#' the_lurking_fear <- lovecraftr::the_lurking_fear
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_lurking_fear) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_lurking_fear.rda) to use with R.
#' @md
"the_lurking_fear"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE MOON BOG"
#' @description A dataset containing text of H. P. Lovecraft's "THE MOON BOG"
#' @usage data(the_moon_bog)
#' @format A character vector with 266 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_moon_bog)
#'
#' the_moon_bog <- lovecraftr::the_moon_bog
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_moon_bog) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_moon_bog.rda) to use with R.
#' @md
"the_moon_bog"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE MUSIC OF ERICH ZANN"
#' @description A dataset containing text of H. P. Lovecraft's "THE MUSIC OF ERICH ZANN"
#' @usage data(the_music_of_erich_zann)
#' @format A character vector with 285 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_music_of_erich_zann)
#'
#' the_music_of_erich_zann <- lovecraftr::the_music_of_erich_zann
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_music_of_erich_zann) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_music_of_erich_zann.rda) to use with R.
#' @md
"the_music_of_erich_zann"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE NAMELESS CITY"
#' @description A dataset containing text of H. P. Lovecraft's "THE NAMELESS CITY"
#' @usage data(the_nameless_city)
#' @format A character vector with 418 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_nameless_city)
#'
#' the_nameless_city <- lovecraftr::the_nameless_city
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_nameless_city) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_nameless_city.rda) to use with R.
#' @md
"the_nameless_city"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE OTHER GODS"
#' @description A dataset containing text of H. P. Lovecraft's "THE OTHER GODS"
#' @usage data(the_other_gods)
#' @format A character vector with 160 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_other_gods)
#'
#' the_other_gods <- lovecraftr::the_other_gods
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_other_gods) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_other_gods.rda) to use with R.
#' @md
"the_other_gods"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE OUTSIDER"
#' @description A dataset containing text of H. P. Lovecraft's "THE OUTSIDER"
#' @usage data(the_outsider)
#' @format A character vector with 213 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_outsider)
#'
#' the_outsider <- lovecraftr::the_outsider
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_outsider) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_outsider.rda) to use with R.
#' @md
"the_outsider"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE PICTURE IN THE HOUSE"
#' @description A dataset containing text of H. P. Lovecraft's "THE PICTURE IN THE HOUSE"
#' @usage data(the_picture_in_the_house)
#' @format A character vector with 263 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_picture_in_the_house)
#'
#' the_picture_in_the_house <- lovecraftr::the_picture_in_the_house
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_picture_in_the_house) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_picture_in_the_house.rda) to use with R.
#' @md
"the_picture_in_the_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE QUEST OF IRANON"
#' @description A dataset containing text of H. P. Lovecraft's "THE QUEST OF IRANON"
#' @usage data(the_quest_of_iranon)
#' @format A character vector with 215 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_quest_of_iranon)
#'
#' the_quest_of_iranon <- lovecraftr::the_quest_of_iranon
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_quest_of_iranon) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_quest_of_iranon.rda) to use with R.
#' @md
"the_quest_of_iranon"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE RATS IN THE WALLS"
#' @description A dataset containing text of H. P. Lovecraft's "THE RATS IN THE WALLS"
#' @usage data(the_rats_in_the_walls)
#' @format A character vector with 691 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_rats_in_the_walls)
#'
#' the_rats_in_the_walls <- lovecraftr::the_rats_in_the_walls
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_rats_in_the_walls) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_rats_in_the_walls.rda) to use with R.
#' @md
"the_rats_in_the_walls"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE SHADOW OUT OF TIME"
#' @description A dataset containing text of H. P. Lovecraft's "THE SHADOW OUT OF TIME"
#' @usage data(the_shadow_out_of_time)
#' @format A character vector with 2,529 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_shadow_out_of_time)
#'
#' the_shadow_out_of_time <- lovecraftr::the_shadow_out_of_time
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_shadow_out_of_time) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_shadow_out_of_time.rda) to use with R.
#' @md
"the_shadow_out_of_time"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE SHADOW OVER INNSMOUTH"
#' @description A dataset containing text of H. P. Lovecraft's "THE SHADOW OVER INNSMOUTH"
#' @usage data(the_shadow_over_innsmouth)
#' @format A character vector with 2,318 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_shadow_over_innsmouth)
#'
#' the_shadow_over_innsmouth <- lovecraftr::the_shadow_over_innsmouth
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_shadow_over_innsmouth) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_shadow_over_innsmouth.rda) to use with R.
#' @md
"the_shadow_over_innsmouth"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE SHUNNED HOUSE"
#' @description A dataset containing text of H. P. Lovecraft's "THE SHUNNED HOUSE"
#' @usage data(the_shunned_house)
#' @format A character vector with 916 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_shunned_house)
#'
#' the_shunned_house <- lovecraftr::the_shunned_house
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_shunned_house) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_shunned_house.rda) to use with R.
#' @md
"the_shunned_house"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE SILVER KEY"
#' @description A dataset containing text of H. P. Lovecraft's "THE SILVER KEY"
#' @usage data(the_silver_key)
#' @format A character vector with 404 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_silver_key)
#'
#' the_silver_key <- lovecraftr::the_silver_key
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_silver_key) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_silver_key.rda) to use with R.
#' @md
"the_silver_key"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE STATEMENT OF RANDOLPH CARTER"
#' @description A dataset containing text of H. P. Lovecraft's "THE STATEMENT OF RANDOLPH CARTER"
#' @usage data(the_statement_of_randolph_carter)
#' @format A character vector with 221 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_statement_of_randolph_carter)
#'
#' the_statement_of_randolph_carter <- lovecraftr::the_statement_of_randolph_carter
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_statement_of_randolph_carter) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_statement_of_randolph_carter.rda) to use with R.
#' @md
"the_statement_of_randolph_carter"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE STRANGE HIGH HOUSE IN THE MIST"
#' @description A dataset containing text of H. P. Lovecraft's "THE STRANGE HIGH HOUSE IN THE MIST"
#' @usage data(the_strange_high_house_in_the_mist)
#' @format A character vector with 289 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_strange_high_house_in_the_mist)
#'
#' the_strange_high_house_in_the_mist <- lovecraftr::the_strange_high_house_in_the_mist
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_strange_high_house_in_the_mist) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_strange_high_house_in_the_mist.rda) to use with R.
#' @md
"the_strange_high_house_in_the_mist"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE STREET"
#' @description A dataset containing text of H. P. Lovecraft's "THE STREET"
#' @usage data(the_street)
#' @format A character vector with 183 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_street)
#'
#' the_street <- lovecraftr::the_street
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_street) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_street.rda) to use with R.
#' @md
"the_street"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE TEMPLE"
#' @description A dataset containing text of H. P. Lovecraft's "THE TEMPLE"
#' @usage data(the_temple)
#' @format A character vector with 450 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_temple)
#'
#' the_temple <- lovecraftr::the_temple
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_temple) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_temple.rda) to use with R.
#' @md
"the_temple"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE TERRIBLE OLD MAN"
#' @description A dataset containing text of H. P. Lovecraft's "THE TERRIBLE OLD MAN"
#' @usage data(the_terrible_old_man)
#' @format A character vector with 87 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_terrible_old_man)
#'
#' the_terrible_old_man <- lovecraftr::the_terrible_old_man
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_terrible_old_man) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_terrible_old_man.rda) to use with R.
#' @md
"the_terrible_old_man"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE THING ON THE DOORSTEP"
#' @description A dataset containing text of H. P. Lovecraft's "THE THING ON THE DOORSTEP"
#' @usage data(the_thing_on_the_doorstep)
#' @format A character vector with 931 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_thing_on_the_doorstep)
#'
#' the_thing_on_the_doorstep <- lovecraftr::the_thing_on_the_doorstep
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_thing_on_the_doorstep) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_thing_on_the_doorstep.rda) to use with R.
#' @md
"the_thing_on_the_doorstep"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE TOMB"
#' @description A dataset containing text of H. P. Lovecraft's "THE TOMB"
#' @usage data(the_tomb)
#' @format A character vector with 366 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_tomb)
#'
#' the_tomb <- lovecraftr::the_tomb
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_tomb) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_tomb.rda) to use with R.
#' @md
"the_tomb"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE TRANSITION OF JUAN ROMERO"
#' @description A dataset containing text of H. P. Lovecraft's "THE TRANSITION OF JUAN ROMERO"
#' @usage data(the_transition_of_juan_romero)
#' @format A character vector with 234 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_transition_of_juan_romero)
#'
#' the_transition_of_juan_romero <- lovecraftr::the_transition_of_juan_romero
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_transition_of_juan_romero) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_transition_of_juan_romero.rda) to use with R.
#' @md
"the_transition_of_juan_romero"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE TREE"
#' @description A dataset containing text of H. P. Lovecraft's "THE TREE"
#' @usage data(the_tree)
#' @format A character vector with 127 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_tree)
#'
#' the_tree <- lovecraftr::the_tree
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_tree) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_tree.rda) to use with R.
#' @md
"the_tree"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE UNNAMABLE"
#' @description A dataset containing text of H. P. Lovecraft's "THE UNNAMABLE"
#' @usage data(the_unnamable)
#' @format A character vector with 239 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_unnamable)
#'
#' the_unnamable <- lovecraftr::the_unnamable
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_unnamable) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_unnamable.rda) to use with R.
#' @md
"the_unnamable"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE VERY OLD FOLK"
#' @description A dataset containing text of H. P. Lovecraft's "THE VERY OLD FOLK"
#' @usage data(the_very_old_folk)
#' @format A character vector with 210 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_very_old_folk)
#'
#' the_very_old_folk <- lovecraftr::the_very_old_folk
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_very_old_folk) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_very_old_folk.rda) to use with R.
#' @md
"the_very_old_folk"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE WHISPERER IN DARKNESS"
#' @description A dataset containing text of H. P. Lovecraft's "THE WHISPERER IN DARKNESS"
#' @usage data(the_whisperer_in_darkness)
#' @format A character vector with 2,303 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_whisperer_in_darkness)
#'
#' the_whisperer_in_darkness <- lovecraftr::the_whisperer_in_darkness
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_whisperer_in_darkness) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_whisperer_in_darkness.rda) to use with R.
#' @md
"the_whisperer_in_darkness"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THE WHITE SHIP"
#' @description A dataset containing text of H. P. Lovecraft's "THE WHITE SHIP"
#' @usage data(the_white_ship)
#' @format A character vector with 200 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(the_white_ship)
#'
#' the_white_ship <- lovecraftr::the_white_ship
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/the_white_ship) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/the_white_ship.rda) to use with R.
#' @md
"the_white_ship"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "THROUGH THE GATES OF THE SILVER KEY"
#' @description A dataset containing text of H. P. Lovecraft's "THROUGH THE GATES OF THE SILVER KEY"
#' @usage data(through_the_gates_of_the_silver_key)
#' @format A character vector with 1,305 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(through_the_gates_of_the_silver_key)
#'
#' through_the_gates_of_the_silver_key <- lovecraftr::through_the_gates_of_the_silver_key
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/through_the_gates_of_the_silver_key) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/through_the_gates_of_the_silver_key.rda) to use with R.
#' @md
"through_the_gates_of_the_silver_key"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of "WHAT THE MOON BRINGS"
#' @description A dataset containing text of H. P. Lovecraft's "WHAT THE MOON BRINGS"
#' @usage data(what_the_moon_brings)
#' @format A character vector with 60 elements, with roughly 80 characters per line.
#'
#' @examples
#' \dontrun{
#' library(lovecraftr)
#' data(what_the_moon_brings)
#'
#' what_the_moon_brings <- lovecraftr::what_the_moon_brings
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#'   See the [raw text file](https://raw.githubusercontent.com/jrdnbradford/lovecraftr/main/data-raw/corpus/what_the_moon_brings) or download
#'   the [RDA file](https://github.com/jrdnbradford/lovecraftr/raw/main/data/what_the_moon_brings.rda) to use with R.
#' @md
"what_the_moon_brings"

##################################################################################
# This documentation is generated by a script, do not edit by hand
# To update, edit the raw txt in data-raw/corpus and run data-raw/generate_data.R
##################################################################################

#' @title Dataset of Lovecraft's corpus
#' @description A dataset containing text of all the H. P. Lovecraft works available in this package.
#' @usage data(lovecraft)
#' @format A tibble with 43,347 rows and 2 columns:
#' \describe{
#'   \item{title}{Title of the work}
#'   \item{text}{~80 characters of text from the title}
#' }
#'
#' @examples
#' \dontrun{
#' data(lovecraft)
#' corpus <- lovecraftr::lovecraft
#' }
#' @docType data
#' @keywords datasets
#' @source Public domain.
#' @md
"lovecraft"
