# Workflow derived from https://github.com/quarto-dev/quarto-actions/tree/v2/render
# Ensures that README.md is up to date with README.qmd
# by rendering, committing, and pushing changes to PR
on:
  pull_request:
    paths:
    - 'README.qmd'

name: README-check

permissions:
  contents: write
  pull-requests: write

jobs:
  README-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 1.6.1

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::devtools
            any::dplyr
            any::knitr
            any::readr
            any::rmarkdown
            any::tibble
          extra-packages:
            local::.

      - name: Render README
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: README.qmd

      - name: Update pull request
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: GHA - render `README` from `README.qmd`
          file_pattern: 'README.md'
