# Workflow derived from https://github.com/quarto-dev/quarto-actions/tree/v2/render
on:
  push:
    branches:
      - '**'

name: render-README

permissions:
  contents: write
  pull-requests: write

jobs:
  render-README:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 1.6.1

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::dplyr
          extra-packages:
            local::.

      - name: Render README
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: README.qmd

      - name: Update pull request
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: GHA - render `README` from `README.qmd`
          file_pattern: 'README.md'
